---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Application Versions
description: Takes an upstream version string and returns various version types

inputs:
  upstream-version:
    description: Upstream Version
    required: true

outputs:
  is-valid-semver:
    description: If version is valid semantic versioning
    value: ${{ steps.versions.outputs.is-valid-semver }}
  is-stable-semver:
    description: If version is stable semantic versioning
    value: ${{ steps.versions.outputs.is-stable-semver }}
  semantic:
    description: Semantic Version
    value: ${{ steps.versions.outputs.semantic }}
  raw:
    description: Raw Version
    value: ${{ steps.versions.outputs.raw }}
  upstream:
    description: Upstream Version
    value: ${{ steps.versions.outputs.upstream }}

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version: 24.x

    - name: Install Semver
      shell: bash
      run: npm install semver

    - name: Application Versions
      id: versions
      shell: bash
      run: node "${{ github.action_path }}/versions.js" "${{ inputs.upstream-version }}"
